### ISSUE TITLE
[BUG] Option Allow resources under root should be available for all item templates

### ISSUE THREAD

**Issue by DavidPressman** [psulek/lhqeditor#2]
### Select category
- [x] **LHQ Editor** - Visual Studio Extension
- [ ] **ScaleHQ.WPF.LHQ** - NuGet Package
- [ ] **ScaleHQ.AspNetCore.LHQ** - NuGet Package
(place x inside square brackets to mark category or multiple categories)

### Version
2021.6

### Visual Studio Edition
- [] Visual Studio Community
- [] Visual Studio Pro
- [x] Visual Studio Enterprise
(place x inside square brackets to mark edition or multiple editions)

### Visual Studio Version
- [ ] 2015
- [ ] 2017
- [ ] 2019
- [x] 2022
(place x inside square brackets to mark version or multiple versions)

### Describe Problem
Web Site illustration shows it should be possible to just have resources only (flat structure), not a hierarchical structure of resources within categories. This choice does not exist and I cannot use LHQ until it does.
![What LHQ Should Do](https://user-images.githubusercontent.com/19474422/150787310-d7764b58-0510-47dd-8bc0-0474b289ca91.jpg)

**Comment by psulek** [comment]
Hi @DavidPressman ,

When creating new LHQ file using "New Item..," , only 1 template "Localization file for Typescript applications" supports this **Resources only** option.

![image](https://user-images.githubusercontent.com/2369743/150788020-f7d1f17b-cc0e-4ad9-ad07-a830abf2d6e5.png)

This is due a fact that "Typescript" template does not generate any C# strongly typed classes. All other templates (which generate also C# classes) cannot have resources directly under the root because C# code generator can generate properties with same names (from your resources) as generated one and thus such c# file will not be valid.

Imagine u have root model named "Strings", generated file **Strings.gen.cs** looks like this:

	public partial class Strings
	{
		private static IStringLocalizer _localizer;
		public Strings(IStringLocalizer localizer)
		{
			_localizer = localizer;
		}


		public static string[] AvailableCultures
		{
		    get
			{
                return new string[] { "en" };
			}
		}
	}

And if resources under root (flat structure) is allowed, and u add new Resource named **AvailableCultures**, LHQ generator will generate 2 properties with same name, and thus break project compilation.

Hopefully i properly describe why u cant have "flat structure" for C# projects. 

Workaround:
You can add 1 subcategory to root and add resources to that category and that category only. I know it is not the same but close enough?

**Comment by DavidPressman** [comment]
Thank you for the explanation.
Unfortunately, the forced use of categories prevents me from directing the resource managers of third-party controls (of which my app has several) to use my own, resulting in numerous auxiliary files for each language.
The only truly workable solution I have found so far is to generate the resx files in VS 2019 using the Multilingual App Toolkit (not available for VS2022) and manually copy new portions (using Beyond Compare) back to those used by VS2022.
Works but a horribly inefficient means.
Hopefully MS will finally release a version for VS2022 or you might even find there is a way.
Nonetheless, thank you for your hard work and quick response.

David Pressman

________________________________

**Comment by psulek** [comment]
@DavidPressman i will try to find out solution for you, will let u know if i have one.

**Comment by psulek** [comment]
@DavidPressman just let u know i am finishing update which lets option **Allow resources under root** be available for all LHQ templates. And when generating resx files there is a check for duplicate resource keys.

**Comment by DavidPressman** [comment]
Thank you or the update. If you would be so kind you might please let me know when you have completed and released those changes. Thank you.

David Pressman
________________________________

**Comment by psulek** [comment]
Fixed in [v2022.1](https://github.com/psulek/lhqeditor/releases/tag/v2022.1)

**Comment by psulek** [comment]
@DavidPressman just released new version.

**Comment by DavidPressman** [comment]
Thank you.

David Pressman
________________________________
